[package]
name = "marketplace_ledger"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/bajoescience/Marketplace.git"
description = "Ledger for the Marketplace DLT"
license = "MIT"

[dependencies]
marketplace_helpers = {path = "../marketplace_helpers", version = "0.1.0"}
marketplace_wallet = {path = "../marketplace_wallet", version = "0.1.0"}
marketplace_primitives = {path = "../marketplace_primitives", version = "0.1.0"}
marketplace_worker = {path = "../marketplace_worker", version = "0.1.0"}
chrono = "0.4.45"
